language: csharp
mono: none
dotnet: 2.0.0
script:
- dotnet build
- dotnet publish .\R6Api\R6Api.csproj -c Release
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: credential.json
  project: "${GOOGLE_PROJECT_ID}"
  no_promote: true
  default: true
  on:
    all_branches: true
