language: csharp
mono: none
dotnet: 2.0.0
script:
- dotnet restore
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: credential.json
  project: "${GOOGLE_PROJECT_ID}"
  default: true
  on:
    all_branches: true
