language: csharp
os: linux
sudo: required
dist: trusty
dotnet: 2.0.0
mono: latest
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
script:
- dotnet restore
- dotnet build
- dotnet publish ./R6Api/R6Api.csproj -c Release
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: credential.json
  project: "${GOOGLE_PROJECT_ID}"
  no_promote: true
  default: true
  on:
    all_branches: true
