language: csharp
os: linux
sudo: required
dist: trusty
dotnet: 2.0.0
mono: latest
env:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true
before_install:
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file credential.json
install:
 - gcloud config set project $GOOGLE_PROJECT_ID
script:
  - ./build.sh
  - gcloud app deploy app.yaml --promote