version: 1.0.{build}  
build_script:
- ps: .\build.ps1
install:
  - secure-file\tools\secure-file -decrypt ".\credential_appveyor.json.enc" -secret %SECRET%  
  - nuget install secure-file -ExcludeVersion
  - choco install gcloudsdk
  - refreshenv
  - gcloud.cmd components copy-bundled-python>>python_path.txt && SET /p CLOUDSDK_PYTHON=<python_path.txt && DEL python_path.txt
  - gcloud.cmd components update --quiet
  - gcloud.cmd components install beta --quiet
deploy_script:  
- cmd: >-

    gcloud config set project %PROJECT_ID%

    gcloud auth activate-service-account %CLIENT_EMAIL% --key-file=".\credential_appveyor.json"

    gcloud beta app deploy ./app.yaml --quiet