version: '{build}'
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
build_script:
- ps: .\build.ps1
test: off
install:
  - nuget install secure-file -ExcludeVersion
  - choco install gcloudsdk
  - refreshenv
  - gcloud.cmd components copy-bundled-python>>python_path.txt && SET /p CLOUDSDK_PYTHON=<python_path.txt && DEL python_path.txt
  - gcloud.cmd components update --quiet
  - gcloud.cmd components install beta --quiet
deploy_script:
- cmd: >-
    dotnet publish C:/projects/r6api/R6Api.csproj -c Release
    gcloud config set project $PROJECT_ID
    gcloud auth activate-service-account $PROJECT_ID@appspot.gserviceaccount.com --key-file="credential_appveyor.json"
    gcloud beta app deploy src/R6Api/bin/Release/netcoreapp2.0/publish/app.yaml --quiet
    
    